### ISSUE TITLE
Incorrect requirements dumped for LightGBM model

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#113]
Executing this script:
```python
import numpy as np
from lightgbm import LGBMRegressor
import mlem

X, y = np.random.randn(1000, 100), np.random.randn(1000)
model = LGBMRegressor(num_iterations=1)
model.fit(X, y)

mlem.api.save(model, "lightgbm", tmp_sample_data=X)
```

I get this in `mlem.yaml`
- no `lightgbm` and `numpy` twice
- `type: sklearn` -- maybe it should be lightgbm one?

```yaml
artifacts:
- uri: artifacts/data.pkl
model_type:
  methods:
    predict:
      args:
      - name: data
        type_:
          dtype: float64
          shape:
          - null
          - 100
          type: ndarray
      name: predict
      returns:
        dtype: float64
        shape:
        - null
        type: ndarray
      varkw: kwargs
    sklearn_predict:
      args:
      - name: X
        type_:
          dtype: float64
          shape:
          - null
          - 100
          type: ndarray
      - default: false
        name: raw_score
        required: false
        type_:
          ptype: bool
          type: primitive
      - default: 0
        name: start_iteration
        required: false
        type_:
          ptype: int
          type: primitive
      - name: num_iteration
        required: false
        type_:
          ptype: NoneType
          type: primitive
      - default: false
        name: pred_leaf
        required: false
        type_:
          ptype: bool
          type: primitive
      - default: false
        name: pred_contrib
        required: false
        type_:
          ptype: bool
          type: primitive
      name: predict
      returns:
        dtype: float64
        shape:
        - null
        type: ndarray
      varkw: kwargs
  type: sklearn
object_type: model
requirements:
- module: numpy
  type: installable
  version: 1.21.4
- module: numpy
  type: installable
  version: 1.21.4
```
