### ISSUE TITLE
Support links to objects located in git repos

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#12]
Consider different options users will want to use links for:

```
# case: link to git repo, link itself can stored wherever you want
link_type: model
mlem_link:
    path: data/model/mlem.yaml
    root_path: examples/dvc-pipeline
    repo: https://github.com/iterative/mlem-prototype
object_type: link


# case: just link to an object inside local folder with .mlem
link_type: model
mlem_link:
    path: data/model/mlem.yaml
object_type: link


# case: link to external object with fsspec-parsed URI
link_type: model
mlem_link:
    path: github://iterative:mlem-prototype@committed-data/examples/dvc-pipeline/data/model
object_type: link
```

Right now we support reading last two examples, but instead of `mlem_link: path: bla-bla` we expect `mlem_link: path`.
Regarding creation, we support only creating the second link. We need to support these examples:

```
# fsspec-parsed URI (GitHub protocol is only the example, this should support all fsspec-supported protocols)
mlem link github://iterative:mlem-prototype@committed-data/examples/dvc-pipeline/data/model gh_model

# using `repo` and `rev` args
mlem link examples/dvc-pipeline/data/model --repo https://github.com/iterative/mlem-prototype --rev committed-data gh_model
```

We also may flatten keys in yaml to better process this with Pydantic, not sure which option will be better.
