### ISSUE TITLE
Index of dataframes becomes a "feature" persisted by mlem.save 

### ISSUE THREAD

**Issue by drorata** [iterative/mlem#280]
Consider the following:

```python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from mlem.api import save


X, y = load_iris(return_X_y=True, as_frame=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=True, random_state=42
)

X_train.to_pickle("./data/X_train.pkl")
y_train.to_pickle("./data/y_train.pkl")

rf = RandomForestClassifier(n_jobs=2, random_state=42,)
rf.fit(X_train, y_train)

save(
    rf, "rf", sample_data=X_train, description="Random Forest Classifier",
)
```

In this case, the resulting metadata of the model treats the index column as one of the features:

```
- name: data
        type_:
          columns:
          - ''
          - sepal length (cm)
          - sepal width (cm)
          - petal length (cm)
          - petal width (cm)
          dtypes:
          - int64
          - float64
          - float64
          - float64
          - float64
          index_cols:
          - ''
          type: dataframe
```

This is confusing and also leads to practical challenges. For example, when dockerizing and serving the model, the API expect five (5) features and not only four (4) which is the actual number of features used by the model.

![image](https://user-images.githubusercontent.com/2905978/171404003-d926db22-288f-493b-9fb8-7ddb68d118d0.png)

This ticket is a follow up of the discussion started on Discord [here](https://discordapp.com/channels/485586884165107732/981169110811562015).

Going with the suggestion of @mike0sv ([here](https://discordapp.com/channels/485586884165107732/981169110811562015/981529160621113454)) to rest the index does mitigate the issue. However, I'm not sure this behavior is ideal. Misalignment between the features used by the model and those listed in the meta data by MLEM is not desired (or at least very confusing).
