### ISSUE TITLE
Failed attempt to serve PyTorch model

### ISSUE THREAD

**Issue by ankxyz** [iterative/mlem#295]
**Train & saving model code**:

```python
import torch
import math
from mlem.api import save


x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)
loss_fn = torch.nn.MSELoss(reduction='sum')
learning_rate = 1e-6

for t in range(2000):

    y_pred = model(xx)
    loss = loss_fn(y_pred, y)

    if t % 100 == 99:
        print(t, loss.item())

    model.zero_grad()
    loss.backward()

    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

linear_layer = model[0]

print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')


save(
    model,
    'torch_model',
    sample_data=xx,
    description='Example of pytorch model'
)
```

**Environment**:
- OS: Ubuntu 20.04
- Python: 3.8.10
- Python package manager: pip 22.1.2
- mlem: 0.2.3
- pytorch: 1.11.0
- fastapi: 0.78.0
- uvicorn: 0.17.6

**Metafile of `mlem` model**:
```yaml
artifacts:
  data:
    hash: fa0c8b5bbc44d9a19b12d47850609ac5
    size: 1767
    uri: torch_model
description: Example of pytorch model
model_type:
  methods:
    predict:
      args:
      - name: data
        type_:
          dtype: float32
          shape:
          - null
          - 3
          type: torch
      name: predict
      returns:
        dtype: float32
        shape:
        - null
        type: torch
    torch_predict:
      args: []
      name: _call_impl
      returns:
        dtype: float32
        shape:
        - null
        type: torch
      varargs: input
      varkw: kwargs
  type: torch
object_type: model
requirements:
- module: torch
  version: 1.11.0+cu102
```

**Command**:

```bash
mlem serve torch_model fastapi
```

**Ouptut/Error**:

```
⏳️ Loading model from .mlem/model/torch_model.mlem
Starting fastapi server...
❌ Unexpected error: 
Please report it here: <https://github.com/iterative/mlem/issues>
```

Could you please give some simple example how to save and serve `PyTorch` models by `mlem`?
