### ISSUE TITLE
Wrong args for model signatures parsed from funcitons with *args

### ISSUE THREAD

**Issue by mike0sv** [iterative/mlem#532]
eg for torch models:
```
processors:
  model:
    methods:
      __call__:
        args: []
        name: __call__
        returns:
          dtype: float32
          shape:
          - null
          - 1000
          type: torch
        varargs: input
        varkw: kwargs
    type: torch
```
