### ISSUE TITLE
`serve`: custom constructed model is exposed with `predict` and `predict_proba`

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#587]
Tried this with both `pip install mlem==0.4.2` and `pip install -e .` for `main`.

```py
from mlem.core.objects import MlemModel, ModelAnalyzer


    
def whichtype(data):
    return str(type(data))
    
def metrics(dummyarg):
    return 1

    

model = MlemModel()
model.add_processor("whichtype", ModelAnalyzer.analyze(whichtype, sample_data="word"))
model.add_processor("metrics", ModelAnalyzer.analyze(metrics, sample_data="word"))
model.call_orders["whichtype"] = [("whichtype", "__call__")]
model.call_orders["metrics"] = [("metrics", "__call__")]

model.dump("model")
```

then: `mlem serve streamlit -m model` (both with `--standartize` and `--no-standartize`) and what you see:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/6797716/213867061-204d3c06-f711-478f-9d1f-1a7e6634b4d0.png">

I bet this was working at some commit between 0.4.1 and 0.4.2, but now I retried and couldn't find it. 🤷🏻 

now what's interesting, you get the same streamlit interface even if there are 3 call_orders now 🤔 
```py
from mlem.core.objects import MlemModel, ModelAnalyzer



def whichtype(data):
    return str(type(data))

def metrics(dummyarg):
    return 1



model = MlemModel()
model.add_processor("whichtype", ModelAnalyzer.analyze(whichtype, sample_data="word"))
model.add_processor("metrics", ModelAnalyzer.analyze(metrics, sample_data="word"))
model.add_processor("metrics2", ModelAnalyzer.analyze(metrics, sample_data="word"))
model.call_orders["whichtype"] = [("whichtype", "__call__")]
model.call_orders["metrics"] = [("metrics", "__call__")]
model.call_orders["metrics2"] = [("metrics2", "__call__")]

model.dump("model")
```

although the `.mlem` file looks pretty normal:

```yaml
artifacts:
  metrics/data.pkl:
    hash: 0a82b20da6ee46dc82855c8b0e3818d9
    size: 241
    uri: model/metrics
  metrics2/data.pkl:
    hash: 0a82b20da6ee46dc82855c8b0e3818d9
    size: 241
    uri: model/metrics2
  whichtype/data.pkl:
    hash: 18627d016628b662a1500dd844e78152
    size: 308
    uri: model/whichtype
call_orders:
  metrics:
  - - metrics
    - __call__
  metrics2:
  - - metrics2
    - __call__
  whichtype:
  - - whichtype
    - __call__
object_type: model
processors:
  metrics:
    io:
      type: pickle
    methods:
      __call__:
        args:
        - name: dummyarg
          type_:
            ptype: str
            type: primitive
        name: __call__
        returns:
          ptype: int
          type: primitive
    type: callable
  metrics2:
    io:
      type: pickle
    methods:
      __call__:
        args:
        - name: dummyarg
          type_:
            ptype: str
            type: primitive
        name: __call__
        returns:
          ptype: int
          type: primitive
    type: callable
  whichtype:
    io:
      type: pickle
    methods:
      __call__:
        args:
        - name: data
          type_:
            ptype: str
            type: primitive
        name: __call__
        returns:
          ptype: str
          type: primitive
    type: callable
requirements:
- is_package: false
  module: __main__
  name: __main__
  source64zip: eJylkcGKAjEMhu99itBTCzKwcxQ8+AA+gUjptnGdpbUlrcjs029nrM46KCzaS0OS7++fdE/Bg3foGxMIm/D5jSYn6HwMlGFTCptg0S1gvNZH7fofJMYYlMMs7uF86Mwh9xGF1VnL5VghzCc6QsokppKcII+ZOpOEPXnfa/q6xz6qPPPDo7CafAh5yTXaWhUpGEwpkOA3E3zmtNGXQNw6FpC0jw7V4GnFz4Esl09kq82norX+gmT7lqbRzqmSQUrbP7Pvyqq298vgSo3NisvdI/g6YUWngf8JtjOynaOVLR8dS9MQc8l+Ac8h1wI=
  type: custom
```
