### ISSUE TITLE
`mlem deploy flyio` fails due to wrong `fly.toml` generated

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#657]
Under the hood [MLEM calls](https://github.com/iterative/mlem/blob/main/mlem/contrib/flyio/meta.py#L113) `flyctl launch` to generate `fly.toml` config for deployment.

It happens, that sometimes `flyctl launch` generates very short `fly.toml` instead of the expected one. That file doesn't have an instruction for fly to work with `8080` port (or whichever one we specify) and after deployment service doesn't respond to requests.

example of "short"/"wrong" fly.toml:
```toml
app = "art-expert-retry2"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []
```
example of "long"/"correct" one:
```toml
app = "art-expert-retry2"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```

Quick search didn't give me any hint whether we simply don't specify some argument for `flyctl launch` or whether this is a bug in fly we need to wait a fix for.
