### ISSUE TITLE
Bug: Validation error when loading linked model

### ISSUE THREAD

**Issue by igordertigor** [iterative/mlem#668]
I linked a model from a different repository using
```bash
$ mlem link --rev=feature_engine@v0.0.2 --sp="https://github.com/myorg/myrepo/" models/feature_engine models/feature_engine
```
However, I can't load it:
```python
import mlem.api
model = mlem.api.load('models/feature_engine')
```
gives the following (not very useful) error message:
```
INFO: Trying to load all models
ERROR: Failed loading model at models/feature_engine.mlem: 1 validation error for ParsingModel[MlemObject]
__root__ -> __root__ -> model_type
  extra fields not permitted (type=value_error.extra)
ERROR: Failed
```
Importantly, the model loads fine if I am directly inside the `myrepo` repository (except for a warning from the `requests` library).

The mlem-link file is small, so I'm posting it here, in case it's useful:
```yaml
link_type: model
object_type: link
path: models/feature_engine.mlem
project: https://github.com/myorg/myrepo/
rev: feature-engine@v0.0.2
```
